#123 container secret updates
CircleCI-Public/aws-ecs-orb pull request #124
Opened 2021-03-12 04:18 UTC by jychen7

try to fix https://github.com/CircleCI-Public/aws-ecs-orb/issues/123

2021-03-12 04:23 UTC, jychen7 commented
I didn't change the terraform for integration test yet, since I am not sure whether it has the permission to write SSM Parameter Store :D

2021-11-04 12:56 UTC, gmemstr commented
Having trouble validating this orb even though to my eye the YAML appears valid. Grabbing a second pair of eyes so we can get to the bottom of this.

2021-11-04 13:53 UTC, KyleTryon requested changes
This was harder to spot than I would have thought. There are three places where `parameter` is used and must be changed to `parameters`

2021-11-04 13:53 UTC, KyleTryon commented on src/commands/update-service.yml
> +            container-secrets-updates: << parameter.container-secrets-updates >>
parameters*

2021-11-04 13:53 UTC, KyleTryon commented on src/jobs/deploy-service-update.yml
> +      container-secrets-updates: << parameter.container-secrets-updates >>
parameters*

2021-11-04 13:53 UTC, KyleTryon commented on src/jobs/update-task-definition.yml
> +      container-secrets-updates: << parameter.container-secrets-updates >>
parameters*

2021-11-06 01:37 UTC, jychen7 commented on src/commands/update-service.yml
> +            container-secrets-updates: << parameter.container-secrets-updates >>
sorry, my bad, thanks for spotting out

2022-04-03 15:12 UTC, closed without merging