[semver:minor] Add support for tagging of task-def to update-service command
CircleCI-Public/aws-ecs-orb pull request #127
Opened 2021-04-07 00:09 UTC by dgeorges

Fix for https://github.com/CircleCI-Public/aws-ecs-orb/issues/120

If the `task-definition-tags` parameter is specified for the update-service command. The task definition will be updated with the tag specified.

2021-04-09 17:24 UTC, dgeorges commented
@KyleTryon Would you be able to review this change?
my apologies if pinging you directly is not the correct process, but it's unclear how the review process works for external contributors and given your most recent rewrite PR you seem to be the most appropriate reviewer. :)

2021-04-12 17:08 UTC, KyleTryon commented
Thanks for the ping @dgeorges. This looks good 👍 . Could I ask you to add the same parameter to the jobs which use this command as well and pass-through the values?

https://github.com/CircleCI-Public/aws-ecs-orb/blob/master/src/jobs/deploy-service-update.yml


Also, are you aware of any issues with using the `--tags` flag with no values? The tests so far have appeared to pass.

2021-04-12 17:09 UTC, KyleTryon requested changes
https://github.com/CircleCI-Public/aws-ecs-orb/blob/master/src/jobs/deploy-service-update.yml

Update job to include these new changes.

2021-04-12 19:44 UTC, dgeorges commented
> Thanks for the ping @dgeorges. This looks good 👍 . Could I ask you to add the same parameter to the jobs which use this command as well and pass-through the values?
> 
> https://github.com/CircleCI-Public/aws-ecs-orb/blob/master/src/jobs/deploy-service-update.yml
> 
> Also, are you aware of any issues with using the `--tags` flag with no values? The tests so far have appeared to pass.

The --tags flag is required. My testing showed it throws the parsing error below if empty which is protected against with the when clause. A similar error is returned if the value isn't formatted correctly.
`Error parsing parameter '--tags': Expected: '=', received: 'EOF' for input:`

FYI update the documentation for the JSON syntax as well, which I tested.

2021-04-14 14:18 UTC, KyleTryon approved these changes
Glorious 🎉  thank you for your contribution. Testing one last time and merging.

2021-04-16 07:34 UTC, dgeorges commented
awesome! Thanks for the review

2021-04-16 19:51 UTC, merged

2021-04-19 21:13 UTC, dgeorges commented
@KyleTryon Looks like the circleci pipeline timed out on the `codedeploy_fargate_tear-down-test-env` job of the `integration-test_deploy` [workflow](https://app.circleci.com/pipelines/github/CircleCI-Public/aws-ecs-orb/628/workflows/f126081a-6797-4f1a-8a63-77dc1d816ff8) while doing a terraform destroy operation. It passed on the branch though and failed on master about 2 months ago too. So looks like an aws/terraform timing thing and not related to the PR. I think a retry will be sufficient, if you wouldn't mind kicking that off, I don't have permissions.

2021-04-21 06:06 UTC, lokst commented
@dgeorges Thanks for alerting us to the failed build. I've rerun the workflow and your changes have been published as `circleci/aws-ecs@2.2.0`. Thank you for your patience on this!