[semver:minor] Add support for container-secrets-updates w/ fixed shellcheck
CircleCI-Public/aws-ecs-orb pull request #138
Opened 2021-12-09 19:51 UTC by jazwiecki

Based on https://github.com/CircleCI-Public/aws-ecs-orb/pull/124, this should fix the shellcheck so we can get this feature in the orb

2021-12-10 14:47 UTC, KyleTryon requested changes
Thank you for the help! I think there is one tiny change needed, mentioned below.

2021-12-10 14:47 UTC, KyleTryon commented on src/scripts/update-bluegreen-service-via-task-def.sh
> +    if aws deploy wait deployment-successful --deployment-id "${DEPLOYMENT_ID}" then
before the `then` I am fairly certain a semicolon will be needed. 
![image](https://user-images.githubusercontent.com/33272306/145592396-7d72ac27-6815-4735-a1f9-da45eb86354f.png)

2021-12-29 19:04 UTC, jazwiecki commented
@KyleTryon made the change, can you re-review when you have a moment?

2022-01-27 19:39 UTC, jazwiecki commented
@KyleTryon not to be a pest but I think this should be approvable

2022-05-13 22:07 UTC, brivu commented
These shell check errors were addressed in PR #153

2022-05-13 22:07 UTC, closed without merging