feat!: v4.0
CircleCI-Public/aws-ecs-orb pull request #201
Opened 2023-06-14 04:40 UTC by brivu

This `PR` contains the changes required for release of `v4.0` of the `AWS ECS` Orb: 

1. Update variable names to conform with Orb Standardization Guide. 
2. Replace job `images` with the default executor 
3. Minor refactoring

2023-06-14 18:51 UTC, EricRibeiro requested changes

2023-06-14 18:51 UTC, EricRibeiro commented on src/commands/update_task_definition.yml
>          ORB_EVAL_CONTAINER_ENV_VAR_UPDATE: <<parameters.container_env_var_updates>>
Rename to `ORB_STR` and change the relevant scripts accordingly.

2023-06-14 18:51 UTC, EricRibeiro commented on src/commands/update_task_definition.yml
>          ORB_EVAL_CONTAINER_DOCKER_LABEL_UPDATES: << parameters.container_docker_label_updates >>
Same as above.

2023-06-15 16:54 UTC, EricRibeiro requested changes

2023-06-15 16:54 UTC, EricRibeiro commented on src/scripts/get_prev_task.sh
> +# These variables are STRuated so the config file may contain and pass in environment variables to the parameters.
```suggestion
# These variables are evaluated so the config file may contain and pass in environment variables to the parameters.
```

2023-06-15 18:08 UTC, EricRibeiro approved these changes

2023-07-28 05:32 UTC, merged

2023-08-01 21:20 UTC, mbeacom commented
@brivu When might we expect version 4.x to be released?